version: '3.8'

services:
  frontend:
    image: ghcr.io/deenyoro/semiprime-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - api

  api:
    image: ghcr.io/deenyoro/semiprime-api:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://factor:factor_dev_password@db:5432/factordb
      - REDIS_URL=redis://queue:6379/0
      - CELERY_BROKER_URL=redis://queue:6379/0
      - CELERY_RESULT_BACKEND=redis://queue:6379/0
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      - db
      - queue

  worker:
    image: ghcr.io/deenyoro/semiprime-worker:latest
    environment:
      - DATABASE_URL=postgresql://factor:factor_dev_password@db:5432/factordb
      - REDIS_URL=redis://queue:6379/0
      - CELERY_BROKER_URL=redis://queue:6379/0
      - CELERY_RESULT_BACKEND=redis://queue:6379/0
    depends_on:
      - db
      - queue
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 8G

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=factor
      - POSTGRES_PASSWORD=factor_dev_password
      - POSTGRES_DB=factordb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  queue:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
